//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntermediatorBot.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConversationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversationText() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntermediatorBot.Strings.ConversationText", typeof(ConversationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept.
        /// </summary>
        internal static string AcceptButtonTitle {
            get {
                return ResourceManager.GetString("AcceptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the user whose request to accept.
        /// </summary>
        internal static string AcceptConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accepter la requête.
        /// </summary>
        internal static string AcceptConnectionRequestsCardTitle {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acceptez ou refusez la requête: Tapez &quot;{0}&quot; pour accepter, &quot;{1}&quot; pour refuser, ou utilisez les boutons s&apos;ils sont activés.
        /// </summary>
        internal static string AcceptRejectConnectionHint {
            get {
                return ResourceManager.GetString("AcceptRejectConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour ajouter un canal d&apos;aggrégation, tapez &quot;{0}&quot;.
        /// </summary>
        internal static string AddAggregationChannelCommandHint {
            get {
                return ResourceManager.GetString("AddAggregationChannelCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce canal est désormais prèt à recevoir des demandes de connexion..
        /// </summary>
        internal static string AggregationChannelAlreadySet {
            get {
                return ResourceManager.GetString("AggregationChannelAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce canal ne recevra plus de demandes de connexion..
        /// </summary>
        internal static string AggregationChannelRemoved {
            get {
                return ResourceManager.GetString("AggregationChannelRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce canal recevra désormais des demandes de connexion..
        /// </summary>
        internal static string AggregationChannelSet {
            get {
                return ResourceManager.GetString("AggregationChannelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes déjà connecté à l&apos;utilisateur : &quot;{0}&quot;.
        /// </summary>
        internal static string AlreadyConnectedWithUser {
            get {
                return ResourceManager.GetString("AlreadyConnectedWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appliquer à tous.
        /// </summary>
        internal static string ApplyToAll {
            get {
                return ResourceManager.GetString("ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bots.
        /// </summary>
        internal static string Bots {
            get {
                return ResourceManager.GetString("Bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panneau d&apos;administration pour controler les conversations live.
        /// </summary>
        internal static string CommandMenuDescription {
            get {
                return ResourceManager.GetString("CommandMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the command using the buttons below or type the command keyword (&quot;{0}&quot;)/bot handle (&quot;@{1}&quot;) followed by the command and its parameters (if any), for example: &quot;{2}&quot;..
        /// </summary>
        internal static string CommandMenuInstructions {
            get {
                return ResourceManager.GetString("CommandMenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commands.
        /// </summary>
        internal static string CommandMenuTitle {
            get {
                return ResourceManager.GetString("CommandMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command &quot;{0}&quot; not recognized.
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A connection request was made, but the requestor party is null.
        /// </summary>
        internal static string ConnectionRequestMadeButRequestorIsNull {
            get {
                return ResourceManager.GetString("ConnectionRequestMadeButRequestorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, you are not allowed to accept or reject requests.
        /// </summary>
        internal static string ConnectionRequestResponseNotAllowed {
            get {
                return ResourceManager.GetString("ConnectionRequestResponseNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;assistance.
        /// </summary>
        internal static string ConnectionRequestTitle {
            get {
                return ResourceManager.GetString("ConnectionRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To initiate a conversation with an agent, type &quot;{0}&quot;.
        /// </summary>
        internal static string ConnectRequestCommandHint {
            get {
                return ResourceManager.GetString("ConnectRequestCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression des données....
        /// </summary>
        internal static string DeletingAllData {
            get {
                return ResourceManager.GetString("DeletingAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de toutes les données demandée par &quot;0&quot;....
        /// </summary>
        internal static string DeletingAllDataWithCommandIssuer {
            get {
                return ResourceManager.GetString("DeletingAllDataWithCommandIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez dit: {0}.
        /// </summary>
        internal static string EchoMessage {
            get {
                return ResourceManager.GetString("EchoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured (result: {0}).
        /// </summary>
        internal static string ErrorOccuredWithResult {
            get {
                return ResourceManager.GetString("ErrorOccuredWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to find the bot party on aggregation channel &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToFindBotOnAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToFindBotOnAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to find the pending request.
        /// </summary>
        internal static string FailedToFindPendingRequest {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to find a pending request for user &quot;0&quot;: {1}.
        /// </summary>
        internal static string FailedToFindPendingRequestForUserWithErrorMessage {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequestForUserWithErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec lors de l&apos;envoi du message.
        /// </summary>
        internal static string FailedToForwardMessage {
            get {
                return ResourceManager.GetString("FailedToForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to reject pending requests.
        /// </summary>
        internal static string FailedToRejectPendingRequests {
            get {
                return ResourceManager.GetString("FailedToRejectPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to remove aggregation channel.
        /// </summary>
        internal static string FailedToRemoveAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToRemoveAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande invalide.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command parameter invalid or missing.
        /// </summary>
        internal static string InvalidOrMissingCommandParameter {
            get {
                return ResourceManager.GetString("InvalidOrMissingCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, nos agents ne sont pas disponible pour le moment.
        /// </summary>
        internal static string NoAgentsAvailable {
            get {
                return ResourceManager.GetString("NoAgentsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No aggregation channel set up.
        /// </summary>
        internal static string NoAggregationChannel {
            get {
                return ResourceManager.GetString("NoAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No bots stored.
        /// </summary>
        internal static string NoBotsStored {
            get {
                return ResourceManager.GetString("NoBotsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No conversations.
        /// </summary>
        internal static string NoConversations {
            get {
                return ResourceManager.GetString("NoConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No pending requests.
        /// </summary>
        internal static string NoPendingRequests {
            get {
                return ResourceManager.GetString("NoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre requête a été acceptée, vous êtes en relation avec {0}.
        /// </summary>
        internal static string NotifyClientConnected {
            get {
                return ResourceManager.GetString("NotifyClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre conversation avec {0} est terminée.
        /// </summary>
        internal static string NotifyClientDisconnected {
            get {
                return ResourceManager.GetString("NotifyClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre requête a été reçue, veuillez patienter pendant qu&apos;un agent traite votre demande..
        /// </summary>
        internal static string NotifyClientDuplicateRequest {
            get {
                return ResourceManager.GetString("NotifyClientDuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unfortunately your request could not be processed.
        /// </summary>
        internal static string NotifyClientRequestRejected {
            get {
                return ResourceManager.GetString("NotifyClientRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un agent va traiter votre requête.
        /// </summary>
        internal static string NotifyClientWaitForRequestHandling {
            get {
                return ResourceManager.GetString("NotifyClientWaitForRequestHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes désormais connecté à l&apos;utilisateur : &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerConnected {
            get {
                return ResourceManager.GetString("NotifyOwnerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez été deconnecté de l&apos;utilisateur : &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerDisconnected {
            get {
                return ResourceManager.GetString("NotifyOwnerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La requête de l&apos;utilisateur &quot;{0}&quot; a été rejetée.
        /// </summary>
        internal static string NotifyOwnerRequestRejected {
            get {
                return ResourceManager.GetString("NotifyOwnerRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No users stored.
        /// </summary>
        internal static string NoUsersStored {
            get {
                return ResourceManager.GetString("NoUsersStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour voir les commandes disponibles, tapez &quot;{0}&quot;.
        /// </summary>
        internal static string OptionsCommandHint {
            get {
                return ResourceManager.GetString("OptionsCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party &quot;{0}&quot; removed.
        /// </summary>
        internal static string PartyRemoved {
            get {
                return ResourceManager.GetString("PartyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} pending request(s) found.
        /// </summary>
        internal static string PendingRequestsFoundWithCount {
            get {
                return ResourceManager.GetString("PendingRequestsFoundWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejeter tout.
        /// </summary>
        internal static string RejectAll {
            get {
                return ResourceManager.GetString("RejectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejeter.
        /// </summary>
        internal static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejeter.
        /// </summary>
        internal static string RejectConnectionRequestCardTitle {
            get {
                return ResourceManager.GetString("RejectConnectionRequestCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the user whose request to reject.
        /// </summary>
        internal static string RejectConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("RejectConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; on channel &quot;{1}&quot; ({2}).
        /// </summary>
        internal static string RequestorDetailsItem {
            get {
                return ResourceManager.GetString("RequestorDetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request was made, but the details of the requestor party are missing.
        /// </summary>
        internal static string RequestorDetailsMissing {
            get {
                return ResourceManager.GetString("RequestorDetailsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête de l&apos;utilisateur &quot;{0}&quot; sur le canal &quot;{1}&quot;.
        /// </summary>
        internal static string RequestorDetailsTitle {
            get {
                return ResourceManager.GetString("RequestorDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les données de l&apos;utilisateur &quot;{0}&quot; ont été supprimées.
        /// </summary>
        internal static string UserDataDeleted {
            get {
                return ResourceManager.GetString("UserDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur manquant.
        /// </summary>
        internal static string UserNameMissing {
            get {
                return ResourceManager.GetString("UserNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
